### ISSUE TITLE
S3Uploader vs UploaderS3 (from DebugLogUploader)

### ISSUE THREAD

**Issue by ujovlado** [keboola/api-error-control#1]
Nahodou som si vsimol, ze to vlastne mame duplicitne. Nemalo by jedno z toho zaniknut resp. jedno z toho pouzit druhe?

https://github.com/keboola/debug-log-uploader/blob/330f783d615dcf057d1dbbf0bbef78f1fe579d76/src/Keboola/DebugLogUploader/UploaderS3.php

**Comment by odinuv** [comment]
jm, ten debug log uploader se pouziva v syrupu, ten jsem zkopiroval, vyhazel z toho veci, co se nepouzivaly a dal to do balicku s logovanim, cili https://github.com/keboola/debug-log-uploader by mel zaniknout

**Comment by ujovlado** [comment]
No pouziva sa to aj v connection. Ak to ma zaniknut imho bude treba este api-error-control rozsirit a pridat tiez moznost “lokalneho uploadovania”.

**Comment by odinuv** [comment]
aha, no a nebo mu muze zustat tady ten - v podstate teda kazdy potrebuje neco jinyho

**Comment by ujovlado** [comment]
Asi mozu ostat aj oba, nemusime to nasilu zjednocovat. V podstate ma len zaujimalo ako/preco to vzniklo.
